#---------------------------
# Hexo Fluid
# Author: Fluid-dev organization
# Github: https://github.com/fluid-dev/hexo-theme-fluid
#
# Docsï¼šhttps://hexo.fluid-dev.com/docs/guide/
#---------------------------


#---------------------------
# å…¨å±€
# Site
#---------------------------
favicon: /img/favicon.ico # ç½‘ç«™æ ‡ç­¾é¡µçš„ icon

apple_touch_icon: /img/favicon.ico # ç”¨äºè‹¹æœè®¾å¤‡çš„ icon

title_join_string: ' - '  # æµè§ˆå™¨æ ‡ç­¾é¡µä¸­çš„æ ‡é¢˜åˆ†éš”ç¬¦ï¼Œæ•ˆæœï¼š æ–‡ç« å ~ ç«™ç‚¹å
force_https: true  # å¼ºåˆ¶æ‰€æœ‰é“¾æ¥å‡çº§ä¸º HTTPSï¼ˆé€‚ç”¨äºå›¾ç‰‡ç­‰èµ„æºå‡ºç° HTTP æ··å…¥æŠ¥é”™ï¼‰

highlight: # ä»£ç é«˜äº®
  enable: true
  style: 'Atom One Dark'  # ä»¥åœ¨ custom.styl å†…ç½®ï¼Œé«˜äº®æ ·å¼è§ï¼šhttps://highlightjs.org/static/demo/
  bg_color: true  # æ˜¯å¦æ ¹æ® style æ”¹å˜ä»£ç èƒŒæ™¯è‰²ï¼Œ**å¦‚æœ style æ˜¯æ·±è‰²èƒŒæ™¯åˆ«å¿˜äº†å¼€å¯æ­¤é¡¹**
  copy_btn: false  # æ˜¯å¦å¼€å¯å¤åˆ¶ä»£ç çš„æŒ‰é’®

fun_features: # ä¸€äº›å¥½ç©çš„åŠŸèƒ½
  typing: # ä¸º subtitle æ·»åŠ æ‰“å­—æœºæ•ˆæœ
    enable: true
    typeSpeed: 70  # æ‰“å°é€Ÿåº¦ï¼Œæ•°å­—è¶Šå¤§è¶Šæ…¢
    cursorChar: "_" # æ¸¸æ ‡å­—ç¬¦
    loop: false # æ˜¯å¦å¾ªç¯æ’­æ”¾æ•ˆæœ
  anchorjs: # ä¸ºæ–‡ç« å†…å®¹ä¸­çš„æ ‡é¢˜æ·»åŠ é”šå›¾æ ‡
    enable: false
    element: h1,h2,h3,h4,h5,h6
    placement: right # iconæ”¾ç½®çš„ä½ç½®ï¼š left | right
    visible: hover # é»˜è®¤æ‚¬æµ®æ˜¾ç¤ºï¼Œå¯é€‰ï¼šhoverï¼ˆé¼ æ ‡åœ¨å…ƒç´ ä¸Šæ‚¬æµ®æ—¶æ˜¾ç¤ºï¼‰ | alwaysï¼ˆä¸€ç›´æ˜¾ç¤ºï¼‰ | touchï¼ˆç§»åŠ¨ç«¯è§¦æ‘¸æ˜¾ç¤ºï¼‰
    icon: "â¡" # å¯é€‰ï¼šÂ§ | # | â¡ ç­‰ï¼Œç•™ç©ºåˆ™ä¸ºé»˜è®¤æ•ˆæœ
  mouse_click:  # é¼ æ ‡ç‚¹å‡»åŠ¨æ•ˆ
    enable: true
    style: love # ç›®å‰è®¾ç½®ä¸¤ä¸ªå€¼ï¼švaluesï¼ˆä»·å€¼è§‚è¯æ±‡ï¼‰ | loveï¼ˆçˆ±å¿ƒï¼‰

color:  # ä¸»é¢˜é¢œè‰²é…ç½®ï¼Œä¸ä¸€å®šèƒ½æ¯ä¸€å¤„éƒ½ç”Ÿæ•ˆï¼Œå¯èƒ½ä¼šè¢«å±€éƒ¨æ ·å¼è¦†ç›–ï¼Œè¿™ç§æƒ…å†µå»ºè®®ç”¨è‡ªå®šä¹‰ css è§£å†³ã€‚é…è‰²å¯ä»¥åœ¨è¿™è·å¾—å¯å‘ï¼š https://www.webdesignrankings.com/resources/lolcolors/
  body_bg_color: "#eee"             # body èƒŒæ™¯è‰²
  navbar_bg_color: "#2f4154"        # é¡¶éƒ¨èœå•èƒŒæ™¯è‰²
  navbar_text_color: "white"        # é¡¶éƒ¨èœå•å­—ä½“è‰²
  text_color: "#3c4858"             # å…¨å±€å­—ä½“è‰²
  sec_text_color: "#718096"         # å…¨å±€æ¬¡çº§å­—ä½“è‰²ï¼ˆæ‘˜è¦ã€ç®€ä»‹ç­‰ä½ç½®ï¼‰
  post_text_color: "#333"           # æ–‡ç« æ­£æ–‡å­—ä½“è‰²
  post_heading_color: "#1a202c"     # æ–‡ç« æ ‡é¢˜æ ‡ç­¾å­—ä½“è‰²ï¼ˆh1 h2 h3...ï¼‰
  link_color: "#3c4858"             # è¶…é“¾æ¥å­—ä½“è‰²
  link_hover_color: "#1abc9c"       # è¶…é“¾æ¥æ‚¬æµ®æ—¶å­—ä½“è‰²
  link_hover_bg_color: "#ebedef"    # è¶…é“¾æ¥æ‚¬æµ®èƒŒæ™¯è‰²
  board_color: "#fff"               # ä¸»é¢æ¿èƒŒæ™¯è‰²

font:  # ä¸»é¢˜å­—ä½“é…ç½®
  font_size: 1.1rem # å…¨å±€å­—å·
  font_family: "'Fira Code', 'Noto Serif SC', serif " # å…¨å±€å­—ä½“
  code_font_size: 100% # ä»£ç çš„å­—å·

custom_js: # æŒ‡å®šè‡ªå®šä¹‰ js æ–‡ä»¶è·¯å¾„ï¼Œè·¯å¾„æ˜¯ç›¸å¯¹ source ç›®å½•ï¼Œå¦‚ /js/custom.js å¯¹åº”å­˜æ”¾ç›®å½• source/js/custom.jsï¼Œæ”¯æŒåˆ—è¡¨
custom_css: /css/custom.css # æŒ‡å®šè‡ªå®šä¹‰ css æ–‡ä»¶è·¯å¾„ï¼Œè·¯å¾„æ˜¯ç›¸å¯¹ source ç›®å½•ï¼Œå¦‚ /css/custom.css åŒä¸Šï¼Œæ”¯æŒåˆ—è¡¨
custom_html: ''  # è‡ªå®šä¹‰åº•éƒ¨ HTML å†…å®¹ï¼ˆä½äº footer ä¸Šæ–¹ï¼‰ï¼Œä¹Ÿå¯ç”¨äºå¤–éƒ¨å¼•å…¥ js css è¿™äº›æ“ä½œï¼Œæ³¨æ„ä¸è¦å’Œ post.custom é…ç½®å†²çª

web_analytics:  # ç½‘é¡µè®¿é—®ç»Ÿè®¡
  enable: true
  baidu: ff40c47e72e383767b9bcd0a82d13218 # ç™¾åº¦ç»Ÿè®¡çš„Keyï¼Œå‚è§ https://tongji.baidu.com/sc-web/10000033910/home/site/getjs?siteId=13751376 ä»£ç è·å–ä¸­ hm.js? åè¾¹çš„å­—ç¬¦ä¸²
  google: # Googleç»Ÿè®¡çš„Tracking IDï¼Œå‚è§ https://analytics.google.com/analytics/web/
  tencent:  # è…¾è®¯ç»Ÿè®¡çš„H5 App idï¼Œå‚è§ https://mta.qq.com/h5/manage/ctr_app_manage (å¼€å¯é«˜çº§åŠŸèƒ½æ‰æœ‰cid)
    sid:
    cid:
  tajs: # è…¾è®¯ç»Ÿè®¡æ—©æœŸç‰ˆç«™ç‚¹ç»Ÿè®¡sIDï¼Œå‚è§ https://ta.qq.com/#/site/list
  woyaola:  # 51.laç«™ç‚¹ç»Ÿè®¡IDï¼Œå‚è§ https://www.51.la/user/site/index
  cnzz:  # å‹ç›Ÿ/cnzzç«™ç‚¹ç»Ÿè®¡web_idï¼Œå‚è§ https://web.umeng.com/main.php?c=site&a=show

lazyload: # å¯¹é¡µé¢ä¸­çš„å›¾ç‰‡è¿›è¡Œæ‡’åŠ è½½å¤„ç†ï¼Œå¯è§èŒƒå›´å¤–çš„å›¾ç‰‡ä¸ä¼šåŠ è½½
  enable: true
  onlypost: true  # ä»…åœ¨æ–‡ç« é¡µä½¿ç”¨æ‡’åŠ è½½ï¼Œå¼€å¯åå¦‚æœè‡ªå®šä¹‰é¡µé¢éœ€è¦ä½¿ç”¨ï¼Œå¯ä»¥åœ¨ Front-matter é‡ŒæŒ‡å®š `lazyload: true`
  image: https://cdn.jsdelivr.net/gh/337892571/imges@master/BlogSource/loading.svg

daovoice:  # åœ¨çº¿å®¢æœ Daovoice å‚è€ƒï¼šhttp://dashboard.daovoice.io
  enable: false # æ˜¯å¦å¼€å¯åœ¨çº¿å®¢æœèŠå¤©
  appid: ''  # åº”ç”¨IDè®¾ç½®

aplayer:  # éŸ³ä¹æ’­æ”¾å™¨ï¼Œæ³¨æ„ä¸èƒ½ä¸ hexo-tag-aplayer æ’ä»¶å…±ç”¨
  enable: false
  autoplay: false  # éŸ³é¢‘è‡ªåŠ¨æ’­æ”¾
  loop: 'all'  # éŸ³é¢‘å¾ªç¯æ’­æ”¾, å¯é€‰å€¼: 'all', 'one', 'none'
  order: 'random'  # æ’­æ”¾é¡ºåºï¼Œå¯é€‰å€¼: 'list', 'random'
  theme: '#b7daff'  # ä¸»é¢˜è‰²
  songs:  # æ­Œæ›²åˆ—è¡¨ï¼Œå¿…é¡»ä¼ å…¥ä¸‹åˆ—å„å‚æ•°ï¼Œå…¶ä¸­ url ä¸ cover åœ¨æœ¬åœ°éœ€å­˜äº source ç›®å½•ï¼Œæ›´å¤šå‚æ•°è§æ–‡æ¡£ï¼šhttps://aplayer.js.org/#/zh-Hans/?id=%E5%8F%82%E6%95%B0
    - { name: 'ã¨ãªã‚Šã®ãƒˆãƒˆãƒ­', artist: 'ä¼Šè—¤ã‚µãƒã‚³', url: 'https://cdn.jsdelivr.net/gh/Royce2019/img/01.mp3', cover: 'https://cdn.jsdelivr.net/gh/Royce2019/img/img/109951163028865726.jpg' }
    - { name: 'ãã‚ŒãŒã‚ãªãŸã®å¹¸ã›ã¨ã—ã¦ã‚‚ (ã‚«ãƒãƒ¼)', artist: 'rairu', url: 'https://cdn.jsdelivr.net/gh/Royce2019/img/02.mp3', cover: 'https://cdn.jsdelivr.net/gh/Royce2019/img/img/109951163597938340.jpg' }

version:  # ä¸»é¢˜ç‰ˆæœ¬ç›¸å…³
  check: false  # æ¯æ¬¡ç”Ÿæˆé¡µé¢åï¼Œæ£€æµ‹ä¸»é¢˜æ˜¯å¦ä¸ºæœ€æ–°ç‰ˆæœ¬


#---------------------------
# é¡µå¤´
# Header
#---------------------------
navbar:
  blog_title: Lioil's world # å¯¼èˆªæ å·¦ä¾§çš„æ ‡é¢˜ï¼Œä¸ºç©ºåˆ™æŒ‰ hexo config.title æ˜¾ç¤º
  ground_glass:  # å¯¼èˆªæ æ¯›ç»ç’ƒç‰¹æ•ˆï¼Œéƒ¨åˆ†æµè§ˆå™¨ä¸æ”¯æŒä¼šè‡ªåŠ¨ä¸ç”Ÿæ•ˆ
    enable: true
    px: 3  # æ¨¡ç³Šåƒç´ ï¼Œåªèƒ½ä¸ºæ•°å­—ï¼Œæ•°å­—è¶Šå¤§æ¨¡ç³Šåº¦è¶Šé«˜
    alpha: 0.7   # é€æ˜åº¦ï¼Œåªèƒ½ä¸ºæ•°å­—ï¼ŒèŒƒå›´0~1ï¼Œæ•°å­—è¶Šå¤§é€æ˜åº¦è¶Šä½ï¼Œæ³¨æ„é€æ˜è¿‡åº¦å¯èƒ½çœ‹ä¸æ¸…èœå•å­—ä½“
  menu:  # å¯è‡ªè¡Œå¢å‡ï¼Œkey ç”¨æ¥å…³è” languages/*.ymlï¼Œå¦‚ä¸å­˜åœ¨å…³è”åˆ™æ˜¾ç¤º key æœ¬èº«çš„å€¼ï¼Œå¢åŠ  name å¯ä»¥å¼ºåˆ¶æ˜¾ç¤ºæŒ‡å®šåç§°
    # - { key: 'home', link: 'https://www.royce2003.top', icon: 'iconfont icon-home-fill' }
    # - { key: 'archive', link: '/archives/', icon: 'iconfont icon-archive-fill' }
    - { key: 'ç½‘ç›˜', link: 'https://dl.linik.ml/', icon: 'iconfont icon-plane' }
    - { key: 'tag', link: '/tags/', icon: 'iconfont icon-tags-fill' }
    - { key: 'messageboard', link: '/messageboard/', icon: 'iconfont icon-liuyan' }
    - { key: 'links', link: '/links/', icon: 'iconfont icon-link-fill' }
    - { key: 'about', link: '/about/', icon: 'iconfont icon-user-fill' }
    - {
      key: 'explore',
      icon: 'iconfont icon-explore-fill',
      submenu: [
        { key: 'artitalk', link: '/artitalk/', icon: 'iconfont icon-shiguangji' },
        { key: 'archive', link: '/archive/', icon: 'iconfont icon-archive-fill' },
        { key: 'gallery', link: '/gallery/', icon: 'iconfont icon-xiangce1' }
      ]
    }
search: # æœç´¢æ 
  enable: false
  path: /local-search.xml # æ–‡ä»¶å¼•ç”¨åœ°å€ï¼Œé»˜è®¤æ˜¯ä¸‹æ–¹ç”Ÿæˆä½ç½®ï¼Œä¹Ÿå¯ä»¥å°†ç”Ÿæˆåçš„ local-search.xml ä¸Šä¼ åˆ°å…¶å®ƒä½ç½®å¼•ç”¨ï¼Œå¦‚ï¼šhttps://www.example.com/local-search.xml
  generate_path: /local-search.xml # æ–‡ä»¶ç”Ÿæˆä½ç½®ï¼Œå¿…é¡»ä¸ºç›¸å¯¹ä½ç½®
  field: post
  content: true

scroll_down_arrow:  # å‘ä¸‹æ»šåŠ¨çš„ç®­å¤´
  enable: true
  banner_height_limit: 90  # å¤´å›¾é«˜åº¦ä¸å°äºæŒ‡å®šæ¯”ä¾‹ï¼Œæ‰æ˜¾ç¤ºç®­å¤´
  scroll_after_turning_page: true  # ç¿»é¡µåè‡ªåŠ¨æ»šåŠ¨

banner_parallax: true # å¤´å›¾æ»šåŠ¨è§†å·®


#---------------------------
# é¡µè„š
# Footer
#---------------------------
footer:
  statistics:  # ç»Ÿè®¡ç½‘ç«™ PVã€UVï¼Œä½¿ç”¨çš„æ˜¯ä¸è’œå­ï¼Œæ˜¾ç¤ºåœ¨é¡µè„š
    enable: false
    pv_format: "{}&nbsp;æ¬¡å›çœ¸"  # æ˜¾ç¤ºçš„æ–‡æœ¬ï¼Œ{}æ˜¯æ•°å­—çš„å ä½ç¬¦ï¼ˆå¿…é¡»åŒ…å«)ï¼Œä¸‹åŒ
    uv_format: "é‡è§äº†&nbsp;{}&nbsp;ä¸ªå°ä¼™ä¼´"

  beian:  # The footer of China's website policy, other areas keep disable
    enable: true
    icp_text: é—½ICPå¤‡20005437å·-1 # ICPè¯å·
    police_text:  # å…¬å®‰å¤‡æ¡ˆå·ï¼Œä¸å¡«åˆ™åªæ˜¾ç¤ºICP
    police_code:  # å…¬å®‰å¤‡æ¡ˆçš„ç¼–å·ï¼Œç”¨äºURLè·³è½¬æŸ¥è¯¢
    police_icon: /img/police_beian.png # å…¬å®‰å¤‡æ¡ˆçš„å›¾ç‰‡. ä¸ºç©ºæ—¶ä¸æ˜¾ç¤ºå¤‡æ¡ˆå›¾ç‰‡

scroll_top_arrow:  # å‘é¡¶éƒ¨æ»šåŠ¨çš„ç®­å¤´
  enable: true


#---------------------------
# é¦–é¡µ
# Index Page
#---------------------------
index:
  banner_img: https://rmt.dogedoge.com/fetch/royce/storage/bg/1.jpg?fmt=webp  # é¦–é¡µ Banner å¤´å›¾ï¼Œä»¥ä¸‹ç›¸åŒ
  banner_img_height: 100  # å¤´å›¾é«˜åº¦ï¼Œå±å¹•ç™¾åˆ†æ¯”ï¼Œavailable: 0 - 100
  banner_mask_alpha: 0.3  # å¤´å›¾é»‘è‰²è’™ç‰ˆçš„é€æ˜åº¦ï¼Œavailable: 0 - 1.0ï¼Œ 0 æ˜¯å®Œå…¨é€æ˜ï¼ˆæ— è’™ç‰ˆï¼‰ï¼Œ1 æ˜¯å®Œå…¨ä¸é€æ˜
  post_default_img:   # éšæœºé»˜è®¤æ–‡ç« å°é¢å›¾ï¼Œå½“æ²¡æœ‰æŒ‡å®š index_img æ—¶ä¼šä½¿ç”¨è¯¥æ–‡ä»¶å¤¹ä¸­çš„å›¾ç‰‡ï¼Œè‹¥éƒ½ä¸ºç©ºåˆ™ä¸æ˜¾ç¤ºä»»ä½•å›¾ç‰‡
    url: https://cdn.jsdelivr.net/gh/337892571/imges@master/index_img # é»˜è®¤çš„æ–‡ç« å°é¢å›¾æ–‡ä»¶å¤¹
    number: 3 # æ–‡ä»¶å¤¹ä¸­å›¾ç‰‡æ•°é‡ï¼Œå›¾ç‰‡å‘½åä»0å¼€å§‹ 0.jpg 1.jpg 2.jpg
    format: webp # å›¾ç‰‡æ ¼å¼ï¼Œä¿è¯æ–‡ä»¶å¤¹ä¸­å›¾ç‰‡æ ¼å¼ä¸€è‡´
  slogan:  # é¦–é¡µå‰¯æ ‡é¢˜çš„ç‹¬ç«‹è®¾ç½®
    enable: true  # ä¸º false åˆ™ä¸æ˜¾ç¤ºä»»ä½•å†…å®¹
    text: ä»Šæ—¥ä»»åŠ¡ï¼šæ—©èµ· (0/1) # ä¸ºç©ºåˆ™æŒ‰ hexo config.subtitle æ˜¾ç¤º
  auto_excerpt:
    enable: true
  post_url_target: _self  # available: _blank | _self
  post_meta: # æ˜¯å¦æ˜¾ç¤ºæ–‡ç« ä¿¡æ¯ï¼ˆæ—¶é—´ã€åˆ†ç±»ã€æ ‡ç­¾ï¼‰
    date: true
    category: false
    tag: true


# é€šè¿‡ hexo new page å‘½ä»¤åˆ›å»ºçš„é¡µé¢
# Custom Page
page:
  banner_img: https://rmt.dogedoge.com/fetch/royce/storage/bg/1.jpg?fmt=webp
  banner_img_height: 80  # available: 0 - 100
  banner_mask_alpha: 0.3  # available: 0 - 1.0

#---------------------------
# æ–‡ç« é¡µ
# Post Page
#---------------------------
post:  # éƒ¨åˆ†é…ç½®åŒæ—¶æ§åˆ¶è‡ªå®šä¹‰é¡µé¢ï¼Œæ³¨æ„å¤‡æ³¨
  banner_img: https://rmt.dogedoge.com/fetch/royce/storage/bg/1.jpg?fmt=webp
  banner_img_height: 80  # available: 0 - 100
  banner_mask_alpha: 0.3  # available: 0 - 1.0
  meta:  # æ–‡ç« æ ‡é¢˜ä¸‹æ–¹çš„ä¿¡æ¯
    date:  # æ–‡ç« æ—¥æœŸ
      enable: true
      format: "ddd MMM DD YYYY"  # æ ¼å¼å‚ç…§ ISO-8601 æ—¥æœŸæ ¼å¼åŒ–
    wordcount:  # å­—æ•°ç»Ÿè®¡
      enable: true
      format: "{}"  # æ˜¾ç¤ºçš„æ–‡æœ¬ï¼Œ{}æ˜¯æ•°å­—çš„å ä½ç¬¦ï¼ˆå¿…é¡»åŒ…å«)ï¼Œä¸‹åŒ
    min2read:  # é˜…è¯»æ—¶é—´
      enable: false
      format: "{} åˆ†é’Ÿ"
      words: 100  # æ¯åˆ†é’Ÿé˜…è¯»å¤šå°‘å­—ï¼Œå¦‚æœæ˜¯æŠ€æœ¯æ–‡ç« ï¼Œå»ºè®®é™ä½
    views:  # é˜…è¯»æ¬¡æ•°ï¼Œç»Ÿè®¡åŸºäºä¸è’œå­
      enable: false
      format: "{} æ¬¡"
  updated:  # åœ¨æ–‡ç« å¼€å¤´æ˜¾ç¤ºæ–‡ç« æ›´æ–°æ—¶é—´ï¼Œè¯¥æ—¶é—´é»˜è®¤æ˜¯ md æ–‡ä»¶æ›´æ–°æ—¶é—´ï¼Œå¯é€šè¿‡ front-matter ä¸­ `updated` æ‰‹åŠ¨æŒ‡å®šï¼ˆå’Œ date ä¸€æ ·æ ¼å¼ï¼‰
    enable: false
    content: æœ¬æ–‡æœ€åæ›´æ–°äºï¼š  # æè¿°æ–‡å­—
    relative: true  # æ˜¯å¦ä½¿ç”¨ç›¸å¯¹æ—¶é—´è¡¨ç¤ºï¼Œæ¯”å¦‚ï¼š"3 å¤©å‰"
  toc:  # æ–‡ç« å³ä¾§ç›®å½•
    enable: true
    headingSelector: h1,h2,h3,h4,h5,h6
    collapseDepth: 0  # å±‚çº§çš„æŠ˜å æ·±åº¦ï¼Œ0 æ˜¯å…¨éƒ¨æŠ˜å ï¼Œ6 æ˜¯å…¨éƒ¨ä¸æŠ˜å 
  copyright:  # ç‰ˆæƒå£°æ˜
    enable: false
    content: 'æœ¬åšå®¢æ–‡ç« é™¤ç‰¹åˆ«å£°æ˜å¤–ï¼Œå‡é‡‡ç”¨ <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh">CC BY-NC-SA 4.0 åè®®</a>ã€‚è½¬è½½è¯·æ³¨æ˜å‡ºå¤„ï¼'
  prev_next:  # æ–‡ç« åº•éƒ¨ä¸Šä¸€ç¯‡ä¸‹ä¸€ç¯‡åŠŸèƒ½
    enable: false
  custom:  # æ–‡ç« åº•éƒ¨è‡ªå®šä¹‰å†…å®¹
    enable: false
    content: '<img src="https://octodex.github.com/images/jetpacktocat.png" class="rounded mx-auto d-block mt-5" style="width:150px; height:150px;">' # è‡ªå®šä¹‰åŒºåŸŸï¼Œæ”¯æŒ HTMLï¼Œå¯è‡ªè¡Œæ’å…¥èµèµç ã€å…¬ä¼—å·äºŒç»´ç ç­‰å†…å®¹
  image_zoom:  # æ–‡ç« å›¾ç‰‡å¯ç‚¹å‡»æ”¾å¤§
    enable: true  # å¼€å¯åæ–‡ç« é»˜è®¤å¯ç”¨ï¼Œè‡ªå®šä¹‰é¡µé¢å¦‚éœ€ä½¿ç”¨ï¼Œéœ€åœ¨ Front-matter ä¸­æŒ‡å®š `image_zoom: true`ï¼Œå¹¶ä¸”å›¾ç‰‡ä½¿ç”¨è¯¥æ ¼å¼æ’å…¥ï¼š<img src="..." zoom />
  math:  # æ•°å­¦å…¬å¼ï¼Œå¼€å¯ä¹‹å‰éœ€è¦æ›´æ¢ Markdown æ¸²æŸ“å™¨ï¼Œå¦åˆ™å¤æ‚å…¬å¼ä¼šæœ‰å…¼å®¹é—®é¢˜ï¼Œå…·ä½“è¯·è§ï¼šhttps://hexo.fluid-dev.com/docs/guide/##latex-æ•°å­¦å…¬å¼
    enable: true  # å¼€å¯åæ–‡ç« é»˜è®¤å¯ç”¨ï¼Œè‡ªå®šä¹‰é¡µé¢å¦‚éœ€ä½¿ç”¨ï¼Œéœ€åœ¨ Front-matter ä¸­æŒ‡å®š `math: true`
    specific: true  # å¼€å¯åï¼Œåªæœ‰åœ¨æ–‡ç«  Front-matter é‡ŒæŒ‡å®š `math: true` æ‰ä¼šåœ¨æ–‡ç« é¡µå¯åŠ¨å…¬å¼è½¬æ¢ï¼Œä»¥ä¾¿åœ¨é¡µé¢ä¸åŒ…å«å…¬å¼æ—¶æé«˜åŠ è½½é€Ÿåº¦
    engine: katex  # å…¬å¼å¼•æ“  available: mathjax | katex
  mermaid:  # æµç¨‹å›¾ï¼ŒåŸºäº mermaid-jsï¼Œæ–‡æ¡£ï¼šhttp://mermaid-js.github.io/mermaid/
    enable: false  # å¼€å¯åæ–‡ç« é»˜è®¤å¯ç”¨ï¼Œè‡ªå®šä¹‰é¡µé¢å¦‚éœ€ä½¿ç”¨ï¼Œéœ€åœ¨ Front-matter ä¸­æŒ‡å®š `mermaid: true`
    specific: false  # å¼€å¯åï¼Œåªæœ‰åœ¨æ–‡ç«  Front-matter é‡ŒæŒ‡å®š `mermaid: true` æ‰ä¼šåœ¨æ–‡ç« é¡µå¯åŠ¨å…¬å¼è½¬æ¢ï¼Œä»¥ä¾¿åœ¨é¡µé¢ä¸åŒ…å«å…¬å¼æ—¶æé«˜åŠ è½½é€Ÿåº¦
    options: { theme: 'default' }  # æ¥å£é€‰é¡¹ï¼Œå…·ä½“å¯è§ï¼šhttp://mermaid-js.github.io/mermaid/#/mermaidAPI
  comments:  # è¯„è®º
    enable: true  # å¼€å¯è¯„è®º
    type: valine  # æŒ‡å®šä½¿ç”¨çš„è¯„è®ºæ¨¡å—  available: disqus | valine | gitalk | utterances | changyan | livere  æ¨è utterances


#---------------------------
# è¯„è®º
# Comments
#---------------------------

# å¼€å¯è¯„è®ºéœ€è¦å…ˆåœ¨ä¸Šæ–¹ post.comments.enable: true

# utterances
# You can install utterances with https://utteranc.es/ and generate your configuration
utterances:
  repo: 
  issue_term: pathname
  label: utterances
  theme: preferred-color-scheme
  crossorigin: anonymous

# Disqus
# å›½å†…ç”¨æˆ·ä¸è¦ç”¨ï¼Œå·²è¢«å¢™
disqus:
  shortname: # your shortname

# Gitalk
# You can get yout ClientID and ClientSecret from https://github.com/settings/applications/new
# More info available at https://github.com/gitalk/gitalk#options
gitalk:
  clientID:                     # GitHub Application Client ID
  clientSecret:                 # GitHub Application Client Secret
  repo:                         # The repo to store comments
  owner:                        # GitHub repository owner. Can be personal user or organization.
  admin:                        # GitHub repo owner and collaborators, only these guys can initialize github issues, should be like "['admin']" or "['admin1','admin2']"
  id: location.pathname         # The unique id of the page. Length must less than 50.
  language: zh-CN               # Localization language key, en, zh-CN and zh-TW are currently available.
  labels: "['Gitalk']"          # GitHub issue labels.
  perPage: 15                   # Pagination size, with maximum 100.
  pagerDirection: last          # Comment sorting direction, available values are last and first.
  distractionFreeMode: false    # Facebook-like distraction free mode.
  createIssueManually: true     # By default, Gitalk will create a corresponding github issue for your every single page automatically when the logined user is belong to the admin users. You can create it manually by setting this option to true.

# Valine
# You can get your appid and appkey from https://leancloud.cn
# More info available at https://valine.js.org
valine:
  appid:   # your leancloud application appid
  appkey:   # your leancloud application appkey
  placeholder: è¯´ç‚¹ä»€ä¹ˆ... # comment box placeholder=
  admin_email: 

# ç•…è¨€
# http://changyan.kuaizhan.com/
changyan:
  appid: ''
  appkey: ''

# Livere æ¥å¿…åŠ›
# You can get your uid from https://www.livere.com/my_Livere
livere:
  uid: ''


#---------------------------
# å½’æ¡£é¡µ
# Archive Page
#---------------------------
archive:
  banner_img: https://rmt.dogedoge.com/fetch/royce/storage/bg/1.jpg?fmt=webp
  banner_img_height: 80  # available: 0 - 100
  banner_mask_alpha: 0.3  # available: 0 - 1.0
  subtitle: è®°ä¸‹å³å°†é€å»çš„é’æ˜¥ï¼Œç•™ä¸‹å³å°†è¿‡å»çš„å¹¸ç¦ # æ‰“å­—æœºå†…å®¹


#---------------------------
# åˆ†ç±»å½’æ¡£é¡µ
# Categories Page
#---------------------------
category:
  banner_img: https://rmt.dogedoge.com/fetch/royce/storage/bg/1.jpg?fmt=webp
  banner_img_height: 80  # available: 0 - 100
  banner_mask_alpha: 0.3  # available: 0 - 1.0
  subtitle:  # æ‰“å­—æœºå†…å®¹


#---------------------------
# æ ‡ç­¾å½’æ¡£é¡µ
# Tags Page
#---------------------------
tag:
  banner_img: https://rmt.dogedoge.com/fetch/royce/storage/bg/1.jpg?fmt=webp
  banner_img_height: 80  # available: 0 - 100
  banner_mask_alpha: 0.3  # available: 0 - 1.0
  subtitle: ä»Šå¤©ä¹Ÿæ˜¯å¼€å¿ƒçš„ä¸€å¤© # æ‰“å­—æœºå†…å®¹
  tagcloud: # æ ‡ç­¾äº‘
    min_font: 15
    max_font: 30
    unit: px  # å­—å·å•ä½
    start_color: "#BBBBEE"
    end_color: "#337ab7"


#---------------------------
# ç•™è¨€æ¿é¡µ
# Messageboard Page
#---------------------------
messageboard:
  banner_img: https://rmt.dogedoge.com/fetch/royce/storage/bg/1.jpg?fmt=webp
  banner_img_height: 80  # available: 0 - 100
  banner_mask_alpha: 0.3  # available: 0 - 1.0
  subtitle: ç•™ä¸‹ä½ çš„è„šå° # æ‰“å­—æœºå†…å®¹


#---------------------------
# å…³äºé¡µ
# About Page
#---------------------------
about:  # å…³äºé¡µéœ€è¦æ‰‹åŠ¨åˆ›å»ºï¼Œå…·ä½“è¯·è§ï¼šhttps://hexo.fluid-dev.com/docs/guide/#å…³äºé¡µ
  banner_img: https://rmt.dogedoge.com/fetch/royce/storage/bg/1.jpg?fmt=webp
  banner_img_height: 80  # available: 0 - 100
  banner_mask_alpha: 0.3  # available: 0 - 1.0
  subtitle: 'ä»Šåæ— è®ºå‘ç”Ÿä»€ä¹ˆäº‹ä¹Ÿå¥½<br>è¿™ä¸ªå·¦æ‰‹ä¸Šçš„â‹¯â‹¯éƒ½æ˜¯åŒä¼´çš„è®°å·' # æ‰“å­—æœºå†…å®¹
  avatar: https://cdn.jsdelivr.net/gh/Royce2019/BlogSource/about/Royce.webp # å¤´åƒ
  name: lioil
  introduce: '<span id="gradient" style="font-family: Sriracha,cursive;">less is more.</span>' # æ”¯æŒ HTML
  icons: # æ›´å¤šå›¾æ ‡å¯ä» https://github.com/fluid-dev/static/blob/master/hexo-theme-fluid/iconfont.png æŸ¥æ‰¾ï¼Œclass ä»£è¡¨å›¾æ ‡çš„ css class
    - { class: '', link: '' }


#---------------------------
# 404é¡µ
# 404 Page
#---------------------------
page404:
  banner_img: https://rmt.dogedoge.com/fetch/royce/storage/bg/1.jpg?fmt=webp
  banner_img_height: 100  # available: 0 - 100
  banner_mask_alpha: 0.3  # available: 0 - 1.0
  subtitle: å–‚ï¼Œå¹ºå¹ºé›¶å—ï¼Ÿè¿™é‡Œçš„é¡µé¢æ‰¾ä¸åˆ°äº† # æ‰“å­—æœºå†…å®¹


# ç«™ç‚¹åœ°å›¾
sitemap:
  path: sitemap.xml

# ç™¾åº¦ç«™ç‚¹åœ°å›¾
baidusitemap:
  path: baidusitemap.xml


#---------------------------
# å‹é“¾é¡µ
# Links Page
#---------------------------
links:
  banner_img: https://rmt.dogedoge.com/fetch/royce/storage/bg/1.jpg?fmt=webp
  banner_img_height: 80  # available: 0 - 100
  banner_mask_alpha: 0.3  # available: 0 - 1.0
  subtitle: æˆ‘ä»¬çš„èˆ¹ä¸Šæ²¡æœ‰æ‰‹ä¸‹ï¼Œåªæœ‰ä¼™ä¼´ # æ‰“å­—æœºå†…å®¹
  defaultlinks:
    - { title: 'skrshadow', intro: 'çº¢é›¨å¤§ä½¬', link: 'www.skrshadow.cn' }
    - { title: '186526çš„åšå®¢', intro: 'ç¾¤å¤§ä½¬', link: '186526.xyz' }
    - { title: 'Dmcimi', intro: 'ç¾¤å¤§ä½¬', link: 'blog.dmcimi.top' }
    - { title: 'è èè èğŸ', intro: 'è èğŸå¤§ä½¬', link: 'wngamebox.cn' }
  friendslinks:
    - { title: '186526çš„åšå®¢', intro: 'ç¾¤å¤§ä½¬', link: '186526.club' }
